#!/bin/bash
#
# cowfortune - fortune and cowsay with a random cow
#
#    Copyright (C) 2012 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. See <http://www.gnu.org/licenses/gpl.html>
#
# Inspired by Linux Mint's mint-fortune
# Some ideas from Nick Daly's cowsay_example in Debian cowsay package

VERSION=0.9.1

cowpath=${COWPATH:-/usr/share/cowsay/cows}
configdir=${XDG_CONFIG_HOME:-"$HOME/.config"}/cowfortune
lastcowfile="$configdir"/lastcow

function choose() { shift $((RANDOM % $#)); echo "$1"; }

while (( $# )); do
	case "$1" in
	--lastcow ) read -r lastcow < "$lastcowfile" ;;
	esac
	shift
done

if [[ "$lastcow" ]]; then
	cow=${cowpath}/${lastcow}.cow
else
	cow=$(choose "$cowpath"/*.cow)
fi

cowbin=$(choose cowsay cowthink)

if ((RANDOM % 2)); then
	cowmode=()
else
	cowmode=( -$(choose b d g p s t w y) )
fi

# Save chosen cow
mkdir -p "$configdir"
echo "$(basename "${cow%.*}")" > "$lastcowfile"

fortune | "$cowbin" -f "$cow" "${cowmode[@]}" && echo
