.TH COWFORTUNE 6 "November  8, 2012"
.SH NAME
cowfortune \- A random cow that says random cookie fortunes. Cool huh?
.SH SYNOPSIS
.B cowfortune
.SH DESCRIPTION
Uses fortune(1) and cowsay(1) to generate a random cow saying random fortune cookies
What else can you ask for?
.SH FILES
cowfortune does not use any file, but it is best used in your ~/.bashrc ,
So everytime you open a new terminal, you're greeted with some wise (or funny) quote
by a humurous random animal. Try it!

System Administrators should also consider putting cowfortune in /etc/bashrc

.SH SEE ALSO
.BR cowsay (1),
.BR fortune (1).
.br
.SH AUTHOR
cowfortune was written by Rodrigo Silva <linux@rodrigosilva.com>.
